name: Elastic Beanstalk Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  qa_deployment:
    name: Deploy to QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to QA
        run: |
          # Add your Elastic Beanstalk deployment commands for QA here
          # Example: eb deploy -e YourQAEnvironment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}

  prod_deployment:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: qa_deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Request Manual Approval (QA to Prod)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "Please approve the deployment from QA to Prod"
        env:
          PR_TITLE: "Manual Approval for Deployment"
        id: approval

      - name: Deploy to Prod
        if: steps.approval.outputs['PR_TITLE'] && github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.action == 'closed'
        run: |
          # Add your Elastic Beanstalk deployment commands for Prod here
          # Example: eb deploy -e YourProdEnvironment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
