name: Elastic Beanstalk Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  qa_deployment:
    name: Deploy to QA
    environment: QA
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install java amd setup maven
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: sonarqube analysis
        run: mvn sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL}} -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: maven build
        run: mvn clean package

      - name: upload to artifact repostory
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: authenticate into aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: copy artifact into s3
        run: aws s3 cp target/*war s3://s3buck-for-diddy

      - name: create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name build-app \
            --source-bundle S3Bucket="s3buck-for-diddy",S3Key="xashy-webapp.war" \
            --version-label "ver-${{ github.sha }}" \
            --description "commit-sha-${{ github.sha }}"

      - name: deploy to elastic beanstalk
        run: aws elasticbeanstalk update-environment --environment-name build-app-env --version-label "ver-${{ github.sha }}" --version-label "ver-${{ github.sha }}"



  prod_deployment:
    name: Deploy to Prod
    environment: Prod
    needs: qa_deployment
    runs-on: ubuntu-latest

    steps:
      - name: authenticate into aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name build-app \
            --source-bundle S3Bucket="s3buck-for-diddy",S3Key="xashy-webapp.war" \
            --description "commit-sha-${{ github.sha }}"

      - name: deploy to elastic beanstalk
        run: aws elasticbeanstalk update-environment --environment-name build-app-prod --version-label "ver-${{ github.sha }}" --version-label "ver-${{ github.sha }}"


    
