name: Elastic Beanstalk Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  qa_deployment:
    name: Deploy to QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to QA
        run: |
          # Add your Elastic Beanstalk deployment commands for QA here
          # Example: eb deploy -e YourQAEnvironment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}

    environment:
      name: QA

  prod_deployment:
    name: Deploy to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Request Manual Approval (QA to Prod)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "Please approve the deployment from QA to Prod"

    environment:
      name: Prod
