name: Build-Deploy-To-ELB

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-test-deploy:
        runs-on: ubuntu-latest
        permissions: 
          ## for github actions to be able to write packages to github packages
          contents: read
          packages: write
        steps:
            - name: clone repositoy 
              uses: actions/checkout@v2

            - name: install java amd setup maven
              uses: actions/setup-java@v3
              with:
                distribution: 'adopt'
                java-version: '11'

            - name: sonarqube analysis
              run: mvn sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL}} -Dsonar.login=${{ secrets.SONAR_TOKEN }}

            - name: maven build
              run: mvn clean package

            - name: upload to artifact repostory
              run: mvn --batch-mode deploy
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: authenticate into aws
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
                
            - name: copy artifact into s3
              run: aws s3 cp target/*war s3://s3buck-for-diddy

            - name: create application version
              run: |
                aws elasticbeanstalk create-application-version \
                  --application-name diddy-qa \
                  --source-bundle S3Bucket="s3buck-for-diddy",S3Key="xashy-webapp.war" \
                  --version-label "ver-${{ github.sha }}" \
                  --description "commit-sha-${{ github.sha }}"

            - name: deploy to elastic beanstalk
              run: aws elasticbeanstalk update-environment --environment-name Diddy-qa-env-2 --version-label "ver-${{ github.sha }}" --version-label "ver-${{ github.sha }}"
