 name: setting up tomcat

 on:
    push:
        branches:
            - main
        
    workflow_dispatch:

 jobs:
    maven_build:
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v3

            - uses: actions/setup-java@v3
              with:
                distribution: 'adopt'
                java-version: '11'
            
            - name: build with maven
              run: mvn package

            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: xashy_app
                path: target/*.war
            
    deploy_artifact:
        runs-on: ubuntu-latest
        needs: maven_build
        steps:
            - name: clone repository
              uses: actions/checkout@v3

            - uses: actions/setup-java@v3
              with:
                distribution: 'adopt'
                java-version: '11'
            
            - name: artifact download
              uses: actions/download-artifact@v3
              with: 
                name: xashy-app
                path: ~/

            - name: key upload
              run: |
                echo ${{ secrets.KEY_FILE}} > ~/tomcat.pem
                sudo chmod 400 ~/tomcat.pem

            - name: uploading
              run: sudo scp -i ~/tomcat.pem -o StrictHostKeyChecking=no ~/*.war ec2-user@52.90.88.33:/opt/tomcat9/webapps


